---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: bdebyl/hugo
    commands:
      - git clone https://gitlab.com/bdebyl/hugo-theme-even.git themes/even
      - hugo build

