---
kind: pipeline
name: default

steps:
  - name: lint
    image: peterdavehello/markdownlint
    commands:
      - markdownlint content/
    trigger:
      event:
        exclude:
          - promote

  - name: build
    image: bdebyl/hugo
    commands:
      - git clone https://github.com/bdebyl/hugo-theme-even.git themes/even
      - hugo
    when:
      event:
        - promote
      target:
        - production

  - name: deploy
    image: bdebyl/awscli
    environment:
      DISTRIBUTION_ID:
        from_secret: aws_distribution_id
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_key
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://bdebyl.net
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths '/*'
    when:
      event:
        - promote
      target:
        - production
---
kind: signature
hmac: 7f15ec618d95cce36ecf999e018b38c056d52538fd6b5c81bdf5c6ce46e0fd21

...
