---
kind: pipeline
name: default

steps:
  - name: build
    image: bdebyl/hugo
    commands:
      - git clone https://github.com/bdebyl/hugo-theme-even.git themes/even
      - hugo

  - name: deploy
    image: bdebyl/awscli
    environment:
      DISTRIBUTION_ID:
        from_secret: aws_distribution_id
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_key
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://bdebyl.net
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths '/*'
    when:
      event:
        - promote
      target:
        - production
---
kind: signature
hmac: 3109d79e76507ab2e9a820522c68b429007ca6f25e0ca16b1b46ed0aba66d23e

...
