stages:
  - build
  - deploy

variables:
  - HUGO_IMAGE_TAG=arm
  - AWS_IMAGE_TAG=0.2

build:
  stage: build
  script:
    - make -e build

deploy:
  stage: deploy
  script:
    - make -e deploy
  only:
    - master
